# Generated by Django 5.2.9 on 2026-01-21 06:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish4hoes', '0005_message_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('trip', 'Trip'), ('party', 'Party'), ('meal', 'Meal'), ('other', 'Other')], default='trip', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='location_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='location_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='trip_id',
            field=models.SlugField(default=django.utils.timezone.now, max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
