# Generated by Django 5.2.9 on 2026-01-21 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish4hoes', '0006_event_created_at_event_event_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carpool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.PositiveIntegerField(default=4)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_carpools', to='fish4hoes.friend')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpools', to='fish4hoes.event')),
            ],
        ),
        migrations.CreateModel(
            name='CarpoolRider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carpool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riders', to='fish4hoes.carpool')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpool_riders', to='fish4hoes.friend')),
            ],
            options={
                'unique_together': {('carpool', 'friend')},
            },
        ),
    ]
